// Auto-generated by cbindgen. Do not edit.

#ifndef SANCTUM_CORE_H
#define SANCTUM_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Load and index a document. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `path` and `model_path` must be valid, null-terminated C strings.
 */
int32_t sanctum_load_document(const char *path, const char *model_path);

/**
 * Ask a question about the loaded document.
 * Returns a JSON string: `{"answer": "...", "error": null}`
 *
 * Caller must free the returned pointer with `sanctum_free_string`.
 *
 * # Safety
 * `question` must be a valid, null-terminated C string.
 * `callback` may be null (no streaming) or a valid function pointer.
 */
char *sanctum_ask(const char *question, void (*callback)(const char*));

/**
 * Free a string returned by sanctum functions.
 *
 * # Safety
 * `ptr` must be a pointer previously returned by a sanctum_* function,
 * or null (in which case this is a no-op).
 */
void sanctum_free_string(char *ptr);

/**
 * Check if a document is currently loaded. Returns 1 if yes, 0 if no.
 */
int32_t sanctum_has_document(void);

/**
 * Clear the current document from memory.
 * Call this when a document is closed or the app is backgrounded
 * to free RAM used by the loaded model and vector store.
 */
void sanctum_clear_document(void);

/**
 * Get information about the loaded document as a JSON string.
 * Returns `{"loaded": true, "char_count": N, "chunk_count": N, "full_context": bool}`
 * or `{"loaded": false}` if no document is loaded.
 *
 * Caller must free the returned pointer with `sanctum_free_string`.
 */
char *sanctum_document_info(void);

/**
 * Check if the embedding model is cached and ready.
 * Returns 1 if the model is ready, 0 if it needs to be downloaded.
 *
 * On first document load, fastembed downloads nomic-embed-text (~137MB).
 * Swift should check this and show a progress indicator if needed.
 */
int32_t sanctum_is_embed_model_ready(void);

#endif  /* SANCTUM_CORE_H */
